name: Deploy to surge

on:
  push:
    branches:
      - master # Set a branch to deploy

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    # Install dependencies
    - name: Install dependencies
      run: npm install
    # Build the project
    - name: Build
      run: npm run build

    # Deploy to surge
    - name: Deploy
      run: npm install --global surge
      run: surge  ./build <your_url_to_deploy> --token <your_surge_token>
